### ISSUE TITLE
Support for descending chat history search

### ISSUE THREAD

**Issue by hajimu01** [langchain-ai/langchain-elastic#37]
Currently, only the earliest messages from the chat history are retrieved due to the ascending order of the search. I think this behavior is not ideal for chatbot use cases. It would be more useful if the chat history could be returned in descending order based on the creation time.

The proposed change:
```python
            result = self.client.search(
                index=self.index,
                query={"term": {"session_id": self.session_id}},
                sort="created_at:desc",
            )
```

**Comment by miguelgrinberg** [comment]
It really isn't clear what langchain expects here. Which order to use seems like an arbitrary choice, so descending does not seem better than ascending, and you will always find valid use cases for both. Just changing the order like you suggest will break existing applications, so that is not really possible.

Maybe an argument needs to be passed in the constructor to specify which order is desired.

**Comment by miguelgrinberg** [comment]
@hajimu01 have you considered reversing the list of chat messages as a workaround?

**Comment by Transrian** [comment]
Hello, I met the same problem ; and for a chatbot usage, only displaying the first 5 interactions (q+a) is not good, the following exchanges are not take into account at all (default search size=10) -> would be better to display the 5 last ?

Would it be envisageable to :
- fetch the results in reverse order: `sort="created_at:desc"`
- reverse the list before returning the value `items.reverse()`

That doesn't change the interaction order, so don't break existing usages, and the latest exchanges are displayed, witch would make more sense ?

**Comment by miguelgrinberg** [comment]
@Transrian we have an open issue that is related to your comment: https://github.com/langchain-ai/langchain-elastic/issues/48. Once that is fixed you will get all the chat messages, not just the first 10.
