### ISSUE TITLE
Passing kwargs to body_func

### ISSUE THREAD

**Issue by gdahia** [langchain-ai/langchain-elastic#41]
Is there a way to pass the `kwargs` passed to `ainvoke` to `body_func` as the code currently is?

It seems to me that there is not, and I have implemented a workaround. However, that seems like a feature that would interest other people as well.

What do you think? I could implement that if it fits the project's roadmap.

**Comment by miguelgrinberg** [comment]
The idea sounds good in principle. Would you like to submit a PR with your suggested change so that we can review it? Thanks!

**Comment by gdahia** [comment]
Sure, I will do that as soon as I can :)
