### ISSUE TITLE
KeyError: 'metadata' when elasticsearch index does not have 'metadata' field, and no "fields" is passed to _search()

### ISSUE THREAD

**Issue by masihsultani** [langchain-ai/langchain-elastic#7]
https://github.com/langchain-ai/langchain-elastic/blob/89fafbe1dc59caa2f3dab81db2143fe20b4b7738/libs/elasticsearch/langchain_elasticsearch/vectorstores.py#L889C1-L913C14

When no fields is passed and elasticsearch index mapping does not have "metadata" field, runs in to KeyError: 'metadata' on line 892 metadata=hit["_source"]["metadata"]. This should be changed to metadata=hit["_source"].get("metadata",{}) or alternatively move this if statement lines(904-905) outside and before if statement 900. Should be:
```
for hit in response["hits"]["hits"]:
            for field in fields:
                if "metadata" not in hit["_source"]:
                        hit["_source"]["metadata"] = {}
                if field in hit["_source"] and field not in [
                    "metadata",
                    self.query_field,
                ]:
                    
                    hit["_source"]["metadata"][field] = hit["_source"][field]

            docs_and_scores.append(
                (
                    doc_builder(hit),
                    hit["_score"],
                )
            )
```

**Comment by maxjakob** [comment]
Closed by https://github.com/langchain-ai/langchain-elastic/pull/8
